### ISSUE TITLE
Нормальное название у проекта будет?

### ISSUE THREAD

**Issue by tpimh** [mrkkrp/ebal#1]
А то даже не смешно как-то.

**Comment by mrkkrp** [comment]
Если название вызывает некоторые ассоциации (хотя, нужно отметь, что такое возможно только у русскоязычных пользователей, что несколько уменьшает количество людей, которые могут быть этим задеты), вы можете использовать произношение производное от английского слова Cabal, соответственно "ибэл". В этом виде название довольно безвредно.

Название само по себе имеет некоторые достоинства:
- краткость;
- созвучность слову Cabal;
- и да, это забавно, но не в пошлом смысле, по крайней мере для меня, потому что это скорее совпадение, что слово, выбранное на основании двух вышеупомянутых качеств, в русском языке (и в некоторых других славянских языках, насколько мне известно), может напоминать спряжение слова рассматриваемого как ненормативное.

Я с трудом могу представить себе практические неудобства для русскоязычной части пользователей, если только они сами не желают придавать такое значение названию этого проекта.

**Comment by lemenkov** [comment]
_"И так у них всё"_ :)

**Comment by mdevaev** [comment]
Спасибо, давно так не смеялись)
