### ISSUE TITLE
`ebal--format-command` mangles cabal components

### ISSUE THREAD

**Issue by ivan-m** [mrkkrp/ebal#11]
From trying to build an executable component (selecting it from the ido list):

```
-*- mode: compilation; default-directory: "~/Haskell/testbench/" -*-
Compilation started at Mon May  8 11:23:00

cabal build exe\:examples
cabal: Unknown build target 'exe:examples'.
There is no executable component 'examples' or component 'exe'.

Compilation exited abnormally with code 1 at Mon May  8 11:23:00
```

The culprit appears to be the call to `shell-quote-argument`.

**Comment by mrkkrp** [comment]
Do you want to open a PR for this? Actually my intention is to start working on a new package that provides magit-like interaction with stack (only), so this will be probably deprecated relatively soon (by the end of summer?).

I may add this to my backlog though, but I won't have time next 2 weeks.

**Comment by mrkkrp** [comment]
Now looking at this, I don't understand how escaping `:` could cause any such issue. Escaped `:` is the same in this context as unescaped, i.e. cabal gets `exe:examples` as argument (shell strips that blackslash). It's even evident on this line:

```
cabal: Unknown build target 'exe:examples'
```

**Comment by mrkkrp** [comment]
I think the problem is rather in the format: it should be `project-name:exe:exe-name`. I'll probably push a fix later today.

**Comment by mrkkrp** [comment]
Should work now.
