### ISSUE TITLE
No longer enables tests or benchmarks?

### ISSUE THREAD

**Issue by ivan-m** [mrkkrp/ebal#7]
`ebal` no longer seems to run `cabal configure` with `--enable-tests --enable-configure`; is it possible to get this back?

**Comment by mrkkrp** [comment]
This is a side effect of added Stack support. Since the tools (Cabal and Stack) have different collection of options, I decided that users will be able to adjust them manually anyway.

It's trivial to get those settings back:

``` emacs-lisp
(push '(configure "--enable-tests" "--enable-benchmarks")
      ebal-global-option-alist)
```

**Comment by ivan-m** [comment]
Fair enough.

I see that you also have support for storing project-local settings in `.ebal` files; any particular reason you don't just use `.dir-local.el` files?

**Comment by mrkkrp** [comment]
Just overlooked `.dir-local.el` feature! If you're comfortable with `.dir-local.el` you can use it instead. One difference is that Ebal detects when contents of `.ebal` file are edited and can re-load it. I don't know if `.dir-local.el` can do the same thing.

**Comment by ivan-m** [comment]
Ahhh, OK; I think `.dir-local.el` is only evaluated when you first load a file.

Anyway, I'll close this now. Thanks for your help!
